export const data = [
  {
    particle: "Todavía",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Todavía",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Todavía",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Todavía",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Todavía",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
  {
    particle: "Tampoco",
    medium: "Oral",
    element: "Verbal",
    direction: "Derecha",
    examples: ["ejemplo 1", "ejemplo 2", "ejemplo 3", "ejemplo 4"],
  },
];
